config/routes.rb
Tuburoku::Application.routes.draw do
  
  resources :tweets
  
  root :to => 'tweets#index'
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :content
  validates :content, :length => { :maximum => 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all
  end
  
  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def create
    @tweet = Tweet.new(params[:tweet])
    if 0 < @tweet.content.length
      if @tweet.save
        redirect_to tweets_path
      else
        redirect_to tweets_path, notice: 'Tweet Failed.'
      end
    else
      @tweet = nil
    end
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update_attributes(params[:tweet])
      redirect_to tweets_path, notice: "Tweet Updated."
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tuburoku</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  <div class="field">
    <%# f.label :content %>
    <%= f.text_area :content, :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

<%= link_to 'timeline', tweets_path %>

app/views/tweets/index.html.erb
<h1>Timeline</h1>

<div id="notice"><%= notice %></div>

<%= form_for(@tweet) do |f| %>
  <div class="field">
    <%# f.label :content %>
    <%= f.text_area :content, :rows => 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<ul>
  <% @tweets.each do |tweet| %>
    <li>
      <%= link_to tweet.content, tweet_path(tweet) %>
      <%= link_to 'Edit', edit_tweet_path(tweet) %>
      <%= link_to 'Delete', tweet, :confirm => 'Are you sure?', :method => :delete %>
    </li>
  <% end %>
</ul>

<script>
$(function() {
  setTimeout(
    function() { $('#notice').fadeOut("slow"); },
    1000);
});
</script>

app/views/tweets/show.html.erb
<p><%= @tweet.content %></p>

<%= link_to 'timeline', tweets_path %>